### ISSUE TITLE
[Help Required] How to get Move Names?

### ISSUE THREAD

**Issue by cglatot** [rubenvereecken/pokemongo-api#39]
Hi, firstly thanks for the API, it's really useful.

I'm having some problems referencing the Move Names, though. I am using:

`party = session.checkInventory().party
 myParty = []
	
	# Get the party and put it into a nicer list
	for pokemon in party:
		IvPercent = ((pokemon.individual_attack + pokemon.individual_defense + pokemon.individual_stamina)*100)/45
		L = [pokedex[pokemon.pokemon_id],pokemon.cp,pokemon.individual_attack,pokemon.individual_defense,pokemon.individual_stamina,IvPercent,pokemon.move_1,pokemon.move_2]`

Everything works okay, except for the `move_1 `and `move_2`. These show up as numbers instead of the names of the moves. I've tried digging through the code, but I cannot figure out how the `session.checkInventory().party` gets the Move **names**.

Any help would be very much appreciated.

**Comment by rubenvereecken** [comment]
That's because the moves are actually numbers. Our protobuf library doesn't map the numbers back to strings (as a comparison, I use a Node library that does). @dmadisetti do you know of any python objects we could try for string enums? They're tremendously useful.

At the Enhanced project we have a Node module that combines all kinds of Pokemon data that we can then use. It's JS, but you could maybe use the JSON files. Check out this one for example for fast moves: https://github.com/PokemonGo-Enhanced/node-pokemongo-data/blob/master/special-moves.json

Careful though, we have two separate move files.

**Comment by cglatot** [comment]
This API library does have the ability to convert the numbers to names, though. If you just run `session.checkInventory()` and output it you get a bunch of information. And for each Pokemon in your party you get the following:

`id: xxxxxxxxxxxxxxx

	pokemon_id: MAGIKARP
	cp: 145
	stamina: 32
	stamina_max: 32
	move_1: SPLASH_FAST
	move_2: STRUGGLE
	height_m: 0.792643606663
	weight_kg: 8.24328136444
	individual_attack: 14
	individual_defense: 13
	individual_stamina: 15
	cp_multiplier: 0.597400009632
	pokeball: ITEM_POKE_BALL
	captured_cell_id: xxxxxxxxxxxxx
	creation_time_ms: 1469450301788
	nickname: "93-14/13/15"
	from_fort: 1`

So it seems there is a way to do it. I just can't find how they are doing it.

**Comment by rubenvereecken** [comment]
Eh terribly sorry. Lemme check

**Comment by cglatot** [comment]
Haha thanks. There is actually a better one that is 15/14/14!

My bot / test account is infinitely better than my real one :(

**Comment by krzys-h** [comment]
You can get the names directly from protobufs:
```python
>>> import POGOProtos.Enums.PokemonMove_pb2 as PokemonMove_pb2
>>> PokemonMove_pb2.PokemonMove.Name(231)
'SPLASH_FAST'
```

**Comment by cglatot** [comment]
Thank you! Works perfectly :D
