### ISSUE TITLE
ERROR - list index out of range: pokemongo-api/pogo/session.py", line 193, in parseDefault

### ISSUE THREAD

**Issue by skyyn377** [rubenvereecken/pokemongo-api#49]
Hi all,
   about every other time i run a call to catch pokemon, or get profile, I get the following:

`Line 40,demo.py - 2016-07-29 14:12:35,856 - INFO - Finding Nearby Pokemon:
Line 198,session.py - 2016-07-29 14:12:35,907 - ERROR - list index out of range
Traceback (most recent call last):
  File "/Users/blarg/Documents/pokemongo-api/pogo/session.py", line 193, in parseDefault
    self._state.eggs.ParseFromString(res.returns[1])
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/google/protobuf/internal/containers.py", line 204, in __getitem__
    return self._values[key]
IndexError: list index out of range`

Once i get the error, if I run the exact same command again, it works.  Thoughts?

**Comment by wolkenflitzer** [comment]
Got the same problem, even after redownloading the API without doing any changes.

**Comment by smilelikebird** [comment]
Seems that we are receiving data which is not recognized for some reason. I received the same kind of ERROR for the badges. I simply added a commentary on the line self._state.badges.ParseFromString(res.returns[3]) of the function parseDefault which is in the file pokemongo-api/pogo/session.py. But of course this is not fix and could have side effect.

**Comment by kwkroll32** [comment]
I got this too and seem to have mitigated it somewhat by adding a sleep command to session.wrapAndRequest. I dropped into that particular function with the python debugger library (pdb) and found that I couldn't replicate the "out of range" error from an interactive session. That is, if the code paused for a second and waited for me to press "continue," it didn't throw this error. Is it possible that there's a need to slow down requests to the server? I'm still having a possibly related problem in trainer.sortCloseForts where self.session somehow becomes NoneType.

**Comment by smilelikebird** [comment]
I still have this problem, what about the other users of this API ? 
Seems that it is because sometime the server is busy so when you send a request you have an empty response. We just have to do some retry before getting a good response. 

Currently what is not efficient I think is that, whatever the catch Exception is we try to reauthenticate the user. Maybe it is better to have a function to check if the session is still available before reauthenticate ? and also during this check, maybe the server busy problem could happen, so after a certain retry we should plan to also reauthenticate to not waste time. 

Hope someone has a true idea about this issue x)

**Comment by progmatik** [comment]
HI kwkroll32 i've got the same problem than you. did you resolved it ?

thanks for your help

**Comment by skyyn377** [comment]
@kwkroll32 adding a sleep command to session.wrapAndRequest seems to be working for me also.

**Comment by smilelikebird** [comment]
@skyyn377 ok me too, but that is also increasing the time of walking.  I put 0.2 sec, +20% time walking.

**Comment by kwkroll32** [comment]
Yes, @smilelikebird, it does add a lot to the walking time, especially since I'm using 1-2 full seconds of sleep. The walkTo function sends several requests to the server to emulate movement, and all of those requests will pass through the wrapAndRequest function. I considered adding an optional argument to wrapAndRequest for the sleep parameter, so walkTo could work as it was intended, and all the other functions that result in malformed responses could wait for a specific amount of time.

If the problem really is related to so many rapid requests, I question whether adding a re-authentication or session check is the solution. Adding that would just make even more requests, which seems like the wrong direction from what I've gathered.

**Comment by dnsBlah** [comment]
I just added like this in actually all the calls:
`cooldown = 1
    while cells == None and cooldown < 7:
        print("[!] No 'Forts' found. Scanning again..")
        time.sleep(2*cooldown)
        cells = session.getMapObjects(bothDirections=True, radius=radius)
        cooldown += 1
`

**Comment by blueachilles** [comment]
I was able to fix this by adding a sleep after each call to getProfile(session) and getInventory(session) in the main in demo.py

**Comment by dnsBlah** [comment]
I'm finding that a specific sleep does not matter much.
My mentioned solution worked for me, specially within mapObjects, using items and pokemon encounter

**Comment by Hedkandi** [comment]
I found that when this error is raised you end up with this:

Line ###,session.py - DATE_AND_TIME - INFO - status_code: 53
request_id: 6999##97##48
api_url: "pgorelease.nianticlabs.com/plfe/515"
returns: ""

Hope it helps. Maybe Status 53 is tied to request interval?

**Comment by dnsBlah** [comment]
error 53 tells you to use a different apiendpoint url
see in response: api_url

**Comment by dnsBlah** [comment]
#74

**Comment by dmadisetti** [comment]
Better error handling is now implented
